apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: exu7z960h-python
  janus-idp.io/tekton: exu7z960h-python
  backstage.io/kubernetes-id: exu7z960h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exu7z960h-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
